Set juju controller to 3.4
canonical/charm-simple-streams pull request #17
Opened 2024-04-12 18:42 UTC by zxhdaze

This is a draft PR to test functional on github.

2024-04-16 14:09 UTC, rgildein requested changes

2024-04-16 14:09 UTC, rgildein commented on .github/workflows/check.yaml
> +    steps:
After some discussion, we agreed that for now we should not move out from bootstack-actions. Can you use them here instead? Thanks.

2024-04-16 14:09 UTC, rgildein commented on .github/workflows/check.yaml
>    func:
Please add concurrency, same as I did in another projects (example [charm-apt-mirror](https://github.com/canonical/charm-apt-mirror/pull/40). Thanks

2024-04-16 15:08 UTC, rgildein approved these changes

2024-04-17 01:46 UTC, Pjack approved these changes

2024-04-17 13:30 UTC, merged